# Generated by Django 4.2.4 on 2023-09-03 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodhabits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='users',
            new_name='user',
        ),
    ]
